"""empty message

Revision ID: 46cf15c1d6b7
Revises: bf8024fd827c
Create Date: 2024-01-15 16:31:15.351767

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "46cf15c1d6b7"
down_revision = "bf8024fd827c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_character_user_id", "character", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_character_user_id", table_name="character")
    # ### end Alembic commands ###
